// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/goairix/llm-proxy/internal/di/provider"
	"github.com/goairix/llm-proxy/internal/infrastructure/config"
)

// Injectors from wire.go:

// Initialize assembles the application dependency graph.
func Initialize(ctx context.Context, cfg *config.Config) (*App, error) {
	logger, err := provider.NewLogger(cfg)
	if err != nil {
		return nil, err
	}
	runtime, err := provider.NewTelemetry(ctx, cfg, logger)
	if err != nil {
		return nil, err
	}
	readiness := provider.NewReadiness()
	stats := provider.NewStats()
	usageObserverFactory := provider.NewObserverFactory()
	openAIHandler, err := provider.NewOpenAIHandler(cfg, runtime)
	if err != nil {
		return nil, err
	}
	anthropicHandler, err := provider.NewAnthropicHandler(cfg, runtime)
	if err != nil {
		return nil, err
	}
	gatewayRuntime := provider.NewGatewayRuntime(cfg, logger)
	credentialCipherRuntime, err := provider.NewCredentialCipherRuntime(cfg)
	if err != nil {
		return nil, err
	}
	unifiedGatewayHandlers, err := provider.NewUnifiedGatewayHandlers(cfg, gatewayRuntime, credentialCipherRuntime, runtime)
	if err != nil {
		return nil, err
	}
	controlPlaneRuntime, err := provider.NewControlPlaneRuntime(cfg, gatewayRuntime, credentialCipherRuntime)
	if err != nil {
		return nil, err
	}
	rootHandler := provider.NewRootHandler(cfg, logger, runtime, readiness, stats, usageObserverFactory, openAIHandler, anthropicHandler, unifiedGatewayHandlers, controlPlaneRuntime)
	server := provider.NewHTTPServer(cfg, rootHandler, logger, readiness)
	app := &App{
		Server:    server,
		Telemetry: runtime,
		Logger:    logger,
		Gateway:   gatewayRuntime,
	}
	return app, nil
}
